// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace TableContentModuleScssNamespace {
    export interface ITableContentModuleScss {
        root: string;
    }
}

declare const TableContentModuleScssModule: TableContentModuleScssNamespace.ITableContentModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: TableContentModuleScssNamespace.ITableContentModuleScss;
};

export = TableContentModuleScssModule;
