// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace TableFooterModuleScssNamespace {
    export interface ITableFooterModuleScss {
        root: string;
    }
}

declare const TableFooterModuleScssModule: TableFooterModuleScssNamespace.ITableFooterModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: TableFooterModuleScssNamespace.ITableFooterModuleScss;
};

export = TableFooterModuleScssModule;
