// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ObjectsModuleScssNamespace {
    export interface IObjectsModuleScss {
        objectList: string;
        root: string;
    }
}

declare const ObjectsModuleScssModule: ObjectsModuleScssNamespace.IObjectsModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ObjectsModuleScssNamespace.IObjectsModuleScss;
};

export = ObjectsModuleScssModule;
