// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ModalConfirmDeletionModuleScssNamespace {
    export interface IModalConfirmDeletionModuleScss {
        backgroundBlurLayer: string;
        modalConfirmButtons: string;
        modalConfirmHeader: string;
        modalConfirmHeaderTitle: string;
        modalConfirmMiddle: string;
        modalConfirmMiddleTop: string;
        modalConfirmWrapper: string;
        modalConfirmWrapperConfirmButton: string;
    }
}

declare const ModalConfirmDeletionModuleScssModule: ModalConfirmDeletionModuleScssNamespace.IModalConfirmDeletionModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ModalConfirmDeletionModuleScssNamespace.IModalConfirmDeletionModuleScss;
};

export = ModalConfirmDeletionModuleScssModule;
