// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace DotsMenuModuleScssNamespace {
    export interface IDotsMenuModuleScss {
        btn: string;
        disabledText: string;
        icon: string;
        itemsWrapper: string;
        textBlock: string;
    }
}

declare const DotsMenuModuleScssModule: DotsMenuModuleScssNamespace.IDotsMenuModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: DotsMenuModuleScssNamespace.IDotsMenuModuleScss;
};

export = DotsMenuModuleScssModule;
