// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ConnectorsListModuleScssNamespace {
    export interface IConnectorsListModuleScss {
        dropdownColumn: string;
        dropdownItem: string;
        folderItemsColumnView: string;
        itemsWrapper: string;
        root: string;
        title: string;
    }
}

declare const ConnectorsListModuleScssModule: ConnectorsListModuleScssNamespace.IConnectorsListModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ConnectorsListModuleScssNamespace.IConnectorsListModuleScss;
};

export = ConnectorsListModuleScssModule;
