// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace SymlayersDesignerModuleScssNamespace {
  export interface ISymlayersDesignerModuleScss {
    container: string;
    content: string;
    contexts: string;
    header: string;
    links: string;
    linksContextWrapper: string;
    root: string;
    schema: string;
    showedTabs: string;
    sidebar: string;
    sidebarWrapper: string;
    tables: string;
  }
}

declare const SymlayersDesignerModuleScssModule: SymlayersDesignerModuleScssNamespace.ISymlayersDesignerModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: SymlayersDesignerModuleScssNamespace.ISymlayersDesignerModuleScss;
};

export = SymlayersDesignerModuleScssModule;
