// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace TableBodyModuleScssNamespace {
    export interface ITableBodyModuleScss {
        loader: string;
        root: string;
    }
}

declare const TableBodyModuleScssModule: TableBodyModuleScssNamespace.ITableBodyModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: TableBodyModuleScssNamespace.ITableBodyModuleScss;
};

export = TableBodyModuleScssModule;
