// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace IconButtonModuleScssNamespace {
    export interface IIconButtonModuleScss {
        active: string;
        icon: string;
        iconButton: string;
        large: string;
        medium: string;
        small: string;
    }
}

declare const IconButtonModuleScssModule: IconButtonModuleScssNamespace.IIconButtonModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: IconButtonModuleScssNamespace.IIconButtonModuleScss;
};

export = IconButtonModuleScssModule;
