// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace UserMenuModuleScssNamespace {
  export interface IUserMenuModuleScss {
    mainBtn: string;
    menuContainer: string;
    menuItem: string;
    note: string;
  }
}

declare const UserMenuModuleScssModule: UserMenuModuleScssNamespace.IUserMenuModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: UserMenuModuleScssNamespace.IUserMenuModuleScss;
};

export = UserMenuModuleScssModule;
