// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ObjectsHeaderModuleScssNamespace {
    export interface IObjectsHeaderModuleScss {
        btnGroup: string;
        iconBtn: string;
        root: string;
        title: string;
    }
}

declare const ObjectsHeaderModuleScssModule: ObjectsHeaderModuleScssNamespace.IObjectsHeaderModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ObjectsHeaderModuleScssNamespace.IObjectsHeaderModuleScss;
};

export = ObjectsHeaderModuleScssModule;
