// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ObjectModuleScssNamespace {
    export interface IObjectModuleScss {
        active: string;
        btn: string;
        title: string;
        wrapper: string;
    }
}

declare const ObjectModuleScssModule: ObjectModuleScssNamespace.IObjectModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ObjectModuleScssNamespace.IObjectModuleScss;
};

export = ObjectModuleScssModule;
