// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace BusinessObjectsModuleScssNamespace {
    export interface IBusinessObjectsModuleScss {
        select: string;
        tables: string;
        text: string;
        top: string;
        wrapper: string;
    }
}

declare const BusinessObjectsModuleScssModule: BusinessObjectsModuleScssNamespace.IBusinessObjectsModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: BusinessObjectsModuleScssNamespace.IBusinessObjectsModuleScss;
};

export = BusinessObjectsModuleScssModule;
