// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ZoomSliderModuleScssNamespace {
    export interface IZoomSliderModuleScss {
        iconWrapper: string;
        percent: string;
        slider: string;
        text: string;
        thumb: string;
        wrapper: string;
    }
}

declare const ZoomSliderModuleScssModule: ZoomSliderModuleScssNamespace.IZoomSliderModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ZoomSliderModuleScssNamespace.IZoomSliderModuleScss;
};

export = ZoomSliderModuleScssModule;
