// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ObjectLayerModuleScssNamespace {
    export interface IObjectLayerModuleScss {
        active: string;
        icon: string;
        menuContainer: string;
        menuItem: string;
        root: string;
        text: string;
    }
}

declare const ObjectLayerModuleScssModule: ObjectLayerModuleScssNamespace.IObjectLayerModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ObjectLayerModuleScssNamespace.IObjectLayerModuleScss;
};

export = ObjectLayerModuleScssModule;
