// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace FormulaEditorModalModuleScssNamespace {
  export interface IFormulaEditorModalModuleScss {
    arrow: string;
    button: string;
    buttonsWrapper: string;
    checkBoxWrapper: string;
    column: string;
    dialog: string;
    dots: string;
    dropDownItem: string;
    form: string;
    formulaBlock: string;
    formulaTextarea: string;
    gearsIcon: string;
    headingFormula: string;
    icon: string;
    input: string;
    itemIcon: string;
    lastBlock: string;
    mainContent: string;
    middleBlock: string;
    modal: string;
    modalBody: string;
    modalContent: string;
    modalHeader: string;
    name: string;
    save: string;
    search: string;
    searchIcon: string;
    selectData: string;
    selectedIconText: string;
    tableName: string;
    testBlock: string;
    testButton: string;
    text: string;
    title: string;
    type: string;
    types: string;
    varBlock: string;
    varSelects: string;
    varTextarea: string;
    varTypes: string;
    varWrapper: string;
    varWrapperForm: string;
    wrapper: string;
    wrapperForm: string;
  }
}

declare const FormulaEditorModalModuleScssModule: FormulaEditorModalModuleScssNamespace.IFormulaEditorModalModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: FormulaEditorModalModuleScssNamespace.IFormulaEditorModalModuleScss;
};

export = FormulaEditorModalModuleScssModule;
