// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace FormulaEditorModalModuleScssNamespace {
  export interface IFormulaEditorModalModuleScss {
    block: string;
    button: string;
    buttonsWrapper: string;
    checkBoxWrapper: string;
    dialog: string;
    dots: string;
    formulaBlock: string;
    formulaTextarea: string;
    gearsIcon: string;
    headingFormula: string;
    icon: string;
    input: string;
    modal: string;
    modalBody: string;
    modalContent: string;
    modalHeader: string;
    optRed: string;
    save: string;
    search: string;
    searchIcon: string;
    selectColumn: string;
    sqlFunctionDescText: string;
    sqlFunctionDescription: string;
    sqlFunctions: string;
    sqlMainContent: string;
    sqlOperators: string;
    sqlTables: string;
    tableColumnName: string;
    tableName: string;
    testBlock: string;
    testButton: string;
  }
}

declare const FormulaEditorModalModuleScssModule: FormulaEditorModalModuleScssNamespace.IFormulaEditorModalModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: FormulaEditorModalModuleScssNamespace.IFormulaEditorModalModuleScss;
};

export = FormulaEditorModalModuleScssModule;
