// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace FormulaEditorModalModuleScssNamespace {
  export interface IFormulaEditorModalModuleScss {
    button: string;
    buttonsWrapper: string;
    dialog: string;
    dots: string;
    formula: string;
    formulaBlock: string;
    input: string;
    modal: string;
    modalBody: string;
    modalContent: string;
  }
}

declare const FormulaEditorModalModuleScssModule: FormulaEditorModalModuleScssNamespace.IFormulaEditorModalModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: FormulaEditorModalModuleScssNamespace.IFormulaEditorModalModuleScss;
};

export = FormulaEditorModalModuleScssModule;
