// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace SemanticLayerModalModuleScssNamespace {
    export interface ISemanticLayerModalModuleScss {
        buttonsWrapper: string;
        cancel: string;
        comments: string;
        description: string;
        dialog: string;
        header: string;
        name: string;
        save: string;
        title: string;
    }
}

declare const SemanticLayerModalModuleScssModule: SemanticLayerModalModuleScssNamespace.ISemanticLayerModalModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: SemanticLayerModalModuleScssNamespace.ISemanticLayerModalModuleScss;
};

export = SemanticLayerModalModuleScssModule;
