// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ModalModuleScssNamespace {
    export interface IModalModuleScss {
        modal: string;
        modalContent: string;
        opacityBox: string;
    }
}

declare const ModalModuleScssModule: ModalModuleScssNamespace.IModalModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ModalModuleScssNamespace.IModalModuleScss;
};

export = ModalModuleScssModule;
