// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace NavItemModuleScssNamespace {
    export interface INavItemModuleScss {
        navigation: string;
        navigationItem: string;
        navigationItemActive: string;
        root: string;
    }
}

declare const NavItemModuleScssModule: NavItemModuleScssNamespace.INavItemModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: NavItemModuleScssNamespace.INavItemModuleScss;
};

export = NavItemModuleScssModule;
