// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace SymlayersListModuleScssNamespace {
    export interface ISymlayersListModuleScss {
        dropdownColumn: string;
        dropdownItem: string;
        folderItemsColumnView: string;
        itemsWrapper: string;
        root: string;
        title: string;
    }
}

declare const SymlayersListModuleScssModule: SymlayersListModuleScssNamespace.ISymlayersListModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: SymlayersListModuleScssNamespace.ISymlayersListModuleScss;
};

export = SymlayersListModuleScssModule;
