// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ReportsModuleScssNamespace {
    export interface IReportsModuleScss {
        dropdownColumn: string;
        dropdownItem: string;
        folderItemsColumnView: string;
        itemsWrapper: string;
        report: string;
        root: string;
        title: string;
    }
}

declare const ReportsModuleScssModule: ReportsModuleScssNamespace.IReportsModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ReportsModuleScssNamespace.IReportsModuleScss;
};

export = ReportsModuleScssModule;
