### Авторизация
POST http://192.168.4.21:8181/?code=CMS.LOGIN&token=null&format=JSON&params={"username":"test","password":"test"}&streamreceiver=null
Content-Type: application/x-www-form-urlencoded

> {% client.global.set("query_id", response.body); %}

<> 2022-06-11T204125.200.txt
<> 2022-06-02T134158.200.txt
<> 2022-06-02T133827.200.txt
<> 2022-06-02T133825.200.txt
<> 2022-06-02T133816.415.json
<> 2022-06-02T133814.415.json

### Получить данные по id
GET http://192.168.4.21:8181/?id={{query_id}}
Content-Type: application/x-www-form-urlencoded

> {% client.global.set("token", response.body.token, "streamreceiver", response.body.streamreceiver); %}


<> 2022-06-11T204648.200.txt
<> 2022-06-11T204134.200.txt
<> 2022-06-02T134158-1.200.txt
<> 2022-06-02T133838.200.txt
<> 2022-06-02T133835.200.txt
<> 2022-06-02T133830.200.txt


### Команда серверу, что пользователь еще не вышел из системы
POST http://192.168.4.21:8181/?code=CMS.ALIVE&params={"token": {{token}}}
Content-Type: application/x-www-form-urlencoded

### Выход из системы
POST http://192.168.4.21:8181/?code=CMS.LOGOUT&params={"token": {{token}}}
Content-Type: application/x-www-form-urlencoded

<> 2022-06-11T204643.200.txt
<> 2022-06-11T204631.415.json

###
