// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace QueryPanelModuleScssNamespace {
    export interface IQueryPanelModuleScss {
        buttonsWrapper: string;
        cancel: string;
        checkBoxWrapper: string;
        content: string;
        dialog: string;
        leftPanel: string;
        modalBody: string;
        modalContent: string;
        rightPanel: string;
        root: string;
        run: string;
        use: string;
    }
}

declare const QueryPanelModuleScssModule: QueryPanelModuleScssNamespace.IQueryPanelModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: QueryPanelModuleScssNamespace.IQueryPanelModuleScss;
};

export = QueryPanelModuleScssModule;
