// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ListTableViewModuleScssNamespace {
    export interface IListTableViewModuleScss {
        listTable: string;
        tableWrapper: string;
    }
}

declare const ListTableViewModuleScssModule: ListTableViewModuleScssNamespace.IListTableViewModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ListTableViewModuleScssNamespace.IListTableViewModuleScss;
};

export = ListTableViewModuleScssModule;
