// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace FiltersModuleScssNamespace {
    export interface IFiltersModuleScss {
        filtersBlock: string;
        wrapper: string;
    }
}

declare const FiltersModuleScssModule: FiltersModuleScssNamespace.IFiltersModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: FiltersModuleScssNamespace.IFiltersModuleScss;
};

export = FiltersModuleScssModule;
