// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace SchemaEditorBlockModuleScssNamespace {
  export interface ISchemaEditorBlockModuleScss {
    arrowBtnClosed: string;
    arrowBtnOpened: string;
    buttonIndents: string;
    buttons: string;
    content: string;
    contentWithSearch: string;
    copyModalWrapper: string;
    create: string;
    dottedBtn: string;
    header: string;
    heading: string;
    icon: string;
    iconsContainer: string;
    input: string;
    inputWrapper: string;
    item: string;
    itemHighlited: string;
    itemIconStyle: string;
    itemsWrapper: string;
    list: string;
    magnifier: string;
    menu: string;
    search: string;
    skeletonLine: string;
    text: string;
    title: string;
    wrapper: string;
    wrapperHighlight: string;
  }
}

declare const SchemaEditorBlockModuleScssModule: SchemaEditorBlockModuleScssNamespace.ISchemaEditorBlockModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: SchemaEditorBlockModuleScssNamespace.ISchemaEditorBlockModuleScss;
};

export = SchemaEditorBlockModuleScssModule;
