// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ListItemModuleScssNamespace {
    export interface IListItemModuleScss {
        active: string;
        icon: string;
        listItem: string;
        name: string;
        tooltip: string;
    }
}

declare const ListItemModuleScssModule: ListItemModuleScssNamespace.IListItemModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ListItemModuleScssNamespace.IListItemModuleScss;
};

export = ListItemModuleScssModule;
