// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace SectionGroupModuleScssNamespace {
  export interface ISectionGroupModuleScss {
    actions: string;
    active: string;
    btn: string;
    root: string;
    select: string;
    title: string;
  }
}

declare const SectionGroupModuleScssModule: SectionGroupModuleScssNamespace.ISectionGroupModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: SectionGroupModuleScssNamespace.ISectionGroupModuleScss;
};

export = SectionGroupModuleScssModule;
