// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace OptionModuleScssNamespace {
    export interface IOptionModuleScss {
        icon: string;
        option: string;
        secondaryText: string;
        text: string;
        textContainer: string;
    }
}

declare const OptionModuleScssModule: OptionModuleScssNamespace.IOptionModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: OptionModuleScssNamespace.IOptionModuleScss;
};

export = OptionModuleScssModule;
