// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace SidebarModuleScssNamespace {
    export interface ISidebarModuleScss {
        actItem: string;
        actListItems: string;
        actObjectLayer: string;
        actTableField: string;
        actTableItem: string;
        disListItems: string;
        dropdownItem: string;
        folderIcon: string;
        iconActive: string;
        icons: string;
        item: string;
        listItem: string;
        listItemField: string;
        listItemFieldWrapper: string;
        listItemName: string;
        listItemWrapper: string;
        listWrapper: string;
        magnifier: string;
        objectDrdnWrapper: string;
        objectItemWrapper: string;
        objectLayer: string;
        objectsData: string;
        root: string;
        search: string;
        searchInput: string;
        searchInputObjects: string;
        tabItem: string;
        tableField: string;
        tableFields: string;
        tableItem: string;
        tooltip: string;
        wrapper: string;
    }
}

declare const SidebarModuleScssModule: SidebarModuleScssNamespace.ISidebarModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: SidebarModuleScssNamespace.ISidebarModuleScss;
};

export = SidebarModuleScssModule;
