// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace SidebarModuleScssNamespace {
    export interface ISidebarModuleScss {
        actItem: string;
        actListItems: string;
        actObjectLayer: string;
        actTableField: string;
        actTableItem: string;
        activeTab: string;
        activeTabObject: string;
        activeTabTable: string;
        combinerObject: string;
        combinerTables: string;
        content: string;
        contentData: string;
        contentObj: string;
        disListItems: string;
        divider: string;
        dropdownItem: string;
        folderIcon: string;
        header: string;
        iconActive: string;
        iconObjectWrap: string;
        iconTableWrap: string;
        icons: string;
        item: string;
        listItem: string;
        listItemField: string;
        listItemFieldWrapper: string;
        listItemName: string;
        listItemWrapper: string;
        listWrapper: string;
        magnifier: string;
        notActiveTab: string;
        notActiveTabObject: string;
        notActiveTabTable: string;
        objectDrdnWrapper: string;
        objectItemWrapper: string;
        objectLayer: string;
        objectsActions: string;
        objectsData: string;
        objectsFilters: string;
        owner: string;
        root: string;
        search: string;
        searchContentData: string;
        searchInput: string;
        searchInputObjects: string;
        tab: string;
        tabObject: string;
        tabTable: string;
        tableActions: string;
        tableField: string;
        tableFields: string;
        tableFilters: string;
        tableItem: string;
        tabs: string;
        tooltip: string;
        wrapper: string;
    }
}

declare const SidebarModuleScssModule: SidebarModuleScssNamespace.ISidebarModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: SidebarModuleScssNamespace.ISidebarModuleScss;
};

export = SidebarModuleScssModule;
