// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace TablesListModuleScssNamespace {
    export interface ITablesListModuleScss {
        actions: string;
        content: string;
        header: string;
        item: string;
        list: string;
        listItem: string;
        root: string;
        title: string;
    }
}

declare const TablesListModuleScssModule: TablesListModuleScssNamespace.ITablesListModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: TablesListModuleScssNamespace.ITablesListModuleScss;
};

export = TablesListModuleScssModule;
