// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace TablesPaneModuleScssNamespace {
    export interface ITablesPaneModuleScss {
        owner: string;
        root: string;
        tables: string;
    }
}

declare const TablesPaneModuleScssModule: TablesPaneModuleScssNamespace.ITablesPaneModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: TablesPaneModuleScssNamespace.ITablesPaneModuleScss;
};

export = TablesPaneModuleScssModule;
