// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ReportFooterModuleScssNamespace {
    export interface IReportFooterModuleScss {
        root: string;
    }
}

declare const ReportFooterModuleScssModule: ReportFooterModuleScssNamespace.IReportFooterModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ReportFooterModuleScssNamespace.IReportFooterModuleScss;
};

export = ReportFooterModuleScssModule;
