// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ServicesModuleScssNamespace {
    export interface IServicesModuleScss {
        form: string;
        groupItem: string;
        groupName: string;
        groupsContainer: string;
        itemDescription: string;
        itemHeader: string;
        itemName: string;
        listInput: string;
    }
}

declare const ServicesModuleScssModule: ServicesModuleScssNamespace.IServicesModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ServicesModuleScssNamespace.IServicesModuleScss;
};

export = ServicesModuleScssModule;
