// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ListNavBarModuleScssNamespace {
    export interface IListNavBarModuleScss {
        breadcrumbs: string;
        breadcrumbsDiv: string;
        breadcrumbsWrapper: string;
        navigation: string;
        navigationActions: string;
        search: string;
    }
}

declare const ListNavBarModuleScssModule: ListNavBarModuleScssNamespace.IListNavBarModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ListNavBarModuleScssNamespace.IListNavBarModuleScss;
};

export = ListNavBarModuleScssModule;
