// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace TablesListItemModuleScssNamespace {
    export interface ITablesListItemModuleScss {
        active: string;
        root: string;
    }
}

declare const TablesListItemModuleScssModule: TablesListItemModuleScssNamespace.ITablesListItemModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: TablesListItemModuleScssNamespace.ITablesListItemModuleScss;
};

export = TablesListItemModuleScssModule;
