// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace PromptPropertiesModuleScssNamespace {
    export interface IPromptPropertiesModuleScss {
        allCheckBoxBlock: string;
        allRadio: string;
        arrow: string;
        button: string;
        byDefaultBlock: string;
        checkBox: string;
        checkBoxWrapper: string;
        dataWindow: string;
        defaultBoxText: string;
        defaultCheckBox: string;
        defaultCheckBoxBlock: string;
        defaultCheckBoxlabel: string;
        dialog: string;
        footerButtons: string;
        input: string;
        inputArrowBlock: string;
        label: string;
        main: string;
        modal: string;
        parameterTypeBlock: string;
        promptTextBlock: string;
        radioLabel: string;
        text: string;
        title: string;
    }
}

declare const PromptPropertiesModuleScssModule: PromptPropertiesModuleScssNamespace.IPromptPropertiesModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: PromptPropertiesModuleScssNamespace.IPromptPropertiesModuleScss;
};

export = PromptPropertiesModuleScssModule;
