// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ReportInfoBlockModuleScssNamespace {
    export interface IReportInfoBlockModuleScss {
        block: string;
        comments: string;
    }
}

declare const ReportInfoBlockModuleScssModule: ReportInfoBlockModuleScssNamespace.IReportInfoBlockModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ReportInfoBlockModuleScssNamespace.IReportInfoBlockModuleScss;
};

export = ReportInfoBlockModuleScssModule;
