// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace SelectModuleScssNamespace {
    export interface ISelectModuleScss {
        content: string;
        isJustify: string;
        select: string;
    }
}

declare const SelectModuleScssModule: SelectModuleScssNamespace.ISelectModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: SelectModuleScssNamespace.ISelectModuleScss;
};

export = SelectModuleScssModule;
