// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace QueryBlockModuleScssNamespace {
    export interface IQueryBlockModuleScss {
        descriptionInput: string;
        divider: string;
        dividerGroup: string;
        gearsGroup: string;
        gearsIcon: string;
        objectQueryBlock: string;
        selectGroup: string;
        testButton: string;
        title: string;
        whereGroup: string;
    }
}

declare const QueryBlockModuleScssModule: QueryBlockModuleScssNamespace.IQueryBlockModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: QueryBlockModuleScssNamespace.IQueryBlockModuleScss;
};

export = QueryBlockModuleScssModule;
