// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ReportModalsModuleScssNamespace {
    export interface IReportModalsModuleScss {
        buttons: string;
        delTitle: string;
        root: string;
        title: string;
        warningMessage: string;
    }
}

declare const ReportModalsModuleScssModule: ReportModalsModuleScssNamespace.IReportModalsModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ReportModalsModuleScssNamespace.IReportModalsModuleScss;
};

export = ReportModalsModuleScssModule;
