// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace UsersModuleScssNamespace {
    export interface IUsersModuleScss {
        root: string;
    }
}

declare const UsersModuleScssModule: UsersModuleScssNamespace.IUsersModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: UsersModuleScssNamespace.IUsersModuleScss;
};

export = UsersModuleScssModule;
