// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ListNavBarActionsModuleScssNamespace {
    export interface IListNavBarActionsModuleScss {
        btnNext: string;
        btnPrev: string;
        btnUp: string;
        navigationActions: string;
    }
}

declare const ListNavBarActionsModuleScssModule: ListNavBarActionsModuleScssNamespace.IListNavBarActionsModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ListNavBarActionsModuleScssNamespace.IListNavBarActionsModuleScss;
};

export = ListNavBarActionsModuleScssModule;
