// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace RecycleBinListModuleScssNamespace {
    export interface IRecycleBinListModuleScss {
        dropdownColumn: string;
        dropdownItem: string;
        folderItemsColumnView: string;
        itemsWrapper: string;
        root: string;
        title: string;
    }
}

declare const RecycleBinListModuleScssModule: RecycleBinListModuleScssNamespace.IRecycleBinListModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: RecycleBinListModuleScssNamespace.IRecycleBinListModuleScss;
};

export = RecycleBinListModuleScssModule;
