// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ReportInfoItemModuleScssNamespace {
    export interface IReportInfoItemModuleScss {
        content: string;
        indents: string;
    }
}

declare const ReportInfoItemModuleScssModule: ReportInfoItemModuleScssNamespace.IReportInfoItemModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ReportInfoItemModuleScssNamespace.IReportInfoItemModuleScss;
};

export = ReportInfoItemModuleScssModule;
