// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace TechInfoBlockModuleScssNamespace {
    export interface ITechInfoBlockModuleScss {
        techInfoInput: string;
        title: string;
    }
}

declare const TechInfoBlockModuleScssModule: TechInfoBlockModuleScssNamespace.ITechInfoBlockModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: TechInfoBlockModuleScssNamespace.ITechInfoBlockModuleScss;
};

export = TechInfoBlockModuleScssModule;
