// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace RolesModuleScssNamespace {
    export interface IRolesModuleScss {
        root: string;
    }
}

declare const RolesModuleScssModule: RolesModuleScssNamespace.IRolesModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: RolesModuleScssNamespace.IRolesModuleScss;
};

export = RolesModuleScssModule;
