// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ReportHeaderModuleScssNamespace {
    export interface IReportHeaderModuleScss {
        root: string;
    }
}

declare const ReportHeaderModuleScssModule: ReportHeaderModuleScssNamespace.IReportHeaderModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ReportHeaderModuleScssNamespace.IReportHeaderModuleScss;
};

export = ReportHeaderModuleScssModule;
