// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ToastModuleScssNamespace {
    export interface IToastModuleScss {
        close: string;
        container: string;
        danger: string;
        modalClose: string;
        notification: string;
        success: string;
        title: string;
        titleWrapper: string;
        toastInRight: string;
    }
}

declare const ToastModuleScssModule: ToastModuleScssNamespace.IToastModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ToastModuleScssNamespace.IToastModuleScss;
};

export = ToastModuleScssModule;
