// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace SqlItemModuleScssNamespace {
    export interface ISqlItemModuleScss {
        checkbox: string;
        indents: string;
        label: string;
        radioWithIndent: string;
        radioWrapper: string;
        wrapper: string;
        wrapperColumn: string;
    }
}

declare const SqlItemModuleScssModule: SqlItemModuleScssNamespace.ISqlItemModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: SqlItemModuleScssNamespace.ISqlItemModuleScss;
};

export = SqlItemModuleScssModule;
