// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace MainModuleScssNamespace {
    export interface IMainModuleScss {
        root: string;
        tabsContainer: string;
        tabsContent: string;
    }
}

declare const MainModuleScssModule: MainModuleScssNamespace.IMainModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: MainModuleScssNamespace.IMainModuleScss;
};

export = MainModuleScssModule;
