// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace PageActionsModuleScssNamespace {
  export interface IPageActionsModuleScss {
    actionWrapper: string;
    actionsContainer: string;
    deactivated: string;
    divider: string;
    filterInput: string;
    pressedButton: string;
  }
}

declare const PageActionsModuleScssModule: PageActionsModuleScssNamespace.IPageActionsModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: PageActionsModuleScssNamespace.IPageActionsModuleScss;
};

export = PageActionsModuleScssModule;
