// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace TreeViewModuleScssNamespace {
    export interface ITreeViewModuleScss {
        container: string;
        head: string;
        node: string;
        nodeActions: string;
        nodeIcon: string;
        toggler: string;
    }
}

declare const TreeViewModuleScssModule: TreeViewModuleScssNamespace.ITreeViewModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: TreeViewModuleScssNamespace.ITreeViewModuleScss;
};

export = TreeViewModuleScssModule;
