// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace DeleteConfirmModalModuleScssNamespace {
    export interface IDeleteConfirmModalModuleScss {
        buttons: string;
        title: string;
    }
}

declare const DeleteConfirmModalModuleScssModule: DeleteConfirmModalModuleScssNamespace.IDeleteConfirmModalModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: DeleteConfirmModalModuleScssNamespace.IDeleteConfirmModalModuleScss;
};

export = DeleteConfirmModalModuleScssModule;
