// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace EditObjectLayerModalModuleScssNamespace {
    export interface IEditObjectLayerModalModuleScss {
        dialog: string;
        input: string;
        name: string;
    }
}

declare const EditObjectLayerModalModuleScssModule: EditObjectLayerModalModuleScssNamespace.IEditObjectLayerModalModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: EditObjectLayerModalModuleScssNamespace.IEditObjectLayerModalModuleScss;
};

export = EditObjectLayerModalModuleScssModule;
