// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace SaveReportModalModuleScssNamespace {
    export interface ISaveReportModalModuleScss {
        buttons: string;
        root: string;
        title: string;
        warningMessage: string;
    }
}

declare const SaveReportModalModuleScssModule: SaveReportModalModuleScssNamespace.ISaveReportModalModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: SaveReportModalModuleScssNamespace.ISaveReportModalModuleScss;
};

export = SaveReportModalModuleScssModule;
