// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace AuditModuleScssNamespace {
    export interface IAuditModuleScss {
        root: string;
    }
}

declare const AuditModuleScssModule: AuditModuleScssNamespace.IAuditModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: AuditModuleScssNamespace.IAuditModuleScss;
};

export = AuditModuleScssModule;
