// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace NotificationModuleScssNamespace {
    export interface INotificationModuleScss {
        root: string;
    }
}

declare const NotificationModuleScssModule: NotificationModuleScssNamespace.INotificationModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: NotificationModuleScssNamespace.INotificationModuleScss;
};

export = NotificationModuleScssModule;
