// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ValueListConnectionBlockModuleScssNamespace {
    export interface IValueListConnectionBlockModuleScss {
        arrow: string;
        availableGroup: string;
        availableTitle: string;
        checkBoxGroup1: string;
        checkBoxGroup2: string;
        checkBoxLabel: string;
        defaultBtn: string;
        defaultLinkInput: string;
        editBtn: string;
        linkBtnGroup: string;
        linkGroup: string;
        listConnectionGroup: string;
        selectData: string;
        showBtn: string;
        useInGroup: string;
        valueListConnectionBlock: string;
    }
}

declare const ValueListConnectionBlockModuleScssModule: ValueListConnectionBlockModuleScssNamespace.IValueListConnectionBlockModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ValueListConnectionBlockModuleScssNamespace.IValueListConnectionBlockModuleScss;
};

export = ValueListConnectionBlockModuleScssModule;
