// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace TooltipModuleScssNamespace {
    export interface ITooltipModuleScss {
        overlay: string;
    }
}

declare const TooltipModuleScssModule: TooltipModuleScssNamespace.ITooltipModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: TooltipModuleScssNamespace.ITooltipModuleScss;
};

export = TooltipModuleScssModule;
