// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace NotificationItemModuleScssNamespace {
    export interface INotificationItemModuleScss {
        advice: string;
        adviceHeader: string;
        adviseArrowDown: string;
        adviseHeaderBox: string;
        adviseText: string;
        button: string;
        message: string;
        messageHeader: string;
        messageText: string;
        reason: string;
        reasonArrowDown: string;
        reasonHeader: string;
        reasonHeaderBox: string;
        reasonText: string;
        root: string;
        title: string;
        topIcon: string;
    }
}

declare const NotificationItemModuleScssModule: NotificationItemModuleScssNamespace.INotificationItemModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: NotificationItemModuleScssNamespace.INotificationItemModuleScss;
};

export = NotificationItemModuleScssModule;
