// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace PropertiesBlockModuleScssNamespace {
    export interface IPropertiesBlockModuleScss {
        arrow: string;
        defaulTypetIcon: string;
        defaultFuncIcon: string;
        defaultIcon: string;
        dropDownDataBlock: string;
        dropDownItem: string;
        dropDownText: string;
        objectFunction: string;
        objectPropertiesBlock: string;
        objectType: string;
        select: string;
        selectData: string;
        selectField: string;
        selectFunc: string;
        selectType: string;
        selectedIconText: string;
        title: string;
    }
}

declare const PropertiesBlockModuleScssModule: PropertiesBlockModuleScssNamespace.IPropertiesBlockModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: PropertiesBlockModuleScssNamespace.IPropertiesBlockModuleScss;
};

export = PropertiesBlockModuleScssModule;
