// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace LogoModuleScssNamespace {
    export interface ILogoModuleScss {
        defaultLogoWrapper: string;
        logoContainer: string;
        logoMain: string;
        pageLogo: string;
        pageTitle: string;
        root: string;
        roottext: string;
    }
}

declare const LogoModuleScssModule: LogoModuleScssNamespace.ILogoModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: LogoModuleScssNamespace.ILogoModuleScss;
};

export = LogoModuleScssModule;
