// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ObjectsPanelModuleScssNamespace {
    export interface IObjectsPanelModuleScss {
        panelListContainer: string;
        root: string;
    }
}

declare const ObjectsPanelModuleScssModule: ObjectsPanelModuleScssNamespace.IObjectsPanelModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ObjectsPanelModuleScssNamespace.IObjectsPanelModuleScss;
};

export = ObjectsPanelModuleScssModule;
