// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ReportDesignerModuleScssNamespace {
    export interface IReportDesignerModuleScss {
        activeTab: string;
        addBtn: string;
        closeIcon: string;
        container: string;
        containerFull: string;
        containerTab1: string;
        containerTab1Formula: string;
        dropdownItem: string;
        footer: string;
        footerCompressed: string;
        formula: string;
        formulaCompressed: string;
        formulaIcons: string;
        formulaTextarea: string;
        iconBtn: string;
        innerContainer: string;
        plus: string;
        root: string;
        tab: string;
        tabs: string;
        tooltip: string;
        wrapper: string;
    }
}

declare const ReportDesignerModuleScssModule: ReportDesignerModuleScssNamespace.IReportDesignerModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ReportDesignerModuleScssNamespace.IReportDesignerModuleScss;
};

export = ReportDesignerModuleScssModule;
