// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ReportDesignerModuleScssNamespace {
    export interface IReportDesignerModuleScss {
        closeIcon: string;
        container: string;
        containerOutline: string;
        content: string;
        formulaEditor: string;
        root: string;
        tab: string;
        tabActive: string;
        tabs: string;
    }
}

declare const ReportDesignerModuleScssModule: ReportDesignerModuleScssNamespace.IReportDesignerModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ReportDesignerModuleScssNamespace.IReportDesignerModuleScss;
};

export = ReportDesignerModuleScssModule;
