// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace SidePanelModuleScssNamespace {
    export interface ISidePanelModuleScss {
        closeIcon: string;
        content: string;
        icon: string;
        navigation: string;
        navigationItem: string;
        navigationItemActive: string;
        objectItem: string;
        root: string;
    }
}

declare const SidePanelModuleScssModule: SidePanelModuleScssNamespace.ISidePanelModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: SidePanelModuleScssNamespace.ISidePanelModuleScss;
};

export = SidePanelModuleScssModule;
