// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace SidePanelModuleScssNamespace {
  export interface ISidePanelModuleScss {
    active: string;
    bgBlock: string;
    btn: string;
    chartObjectItem: string;
    checkBox: string;
    checkBoxWrapper: string;
    closeIcon: string;
    colorPicker: string;
    content: string;
    dropBlock: string;
    droppedObject: string;
    flex: string;
    grad: string;
    heading: string;
    icon: string;
    iconsContainer: string;
    ind: string;
    indents: string;
    label: string;
    navigation: string;
    navigationItem: string;
    navigationItemActive: string;
    objectItem: string;
    rgba: string;
    root: string;
    text: string;
    title: string;
  }
}

declare const SidePanelModuleScssModule: SidePanelModuleScssNamespace.ISidePanelModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: SidePanelModuleScssNamespace.ISidePanelModuleScss;
};

export = SidePanelModuleScssModule;
