// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ColorPickerModuleScssNamespace {
    export interface IColorPickerModuleScss {
        active: string;
        background: string;
        colorSelector: string;
        hidden: string;
        overlay: string;
        title: string;
    }
}

declare const ColorPickerModuleScssModule: ColorPickerModuleScssNamespace.IColorPickerModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ColorPickerModuleScssNamespace.IColorPickerModuleScss;
};

export = ColorPickerModuleScssModule;
