// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ControlModuleScssNamespace {
    export interface IControlModuleScss {
        input: string;
        lastInput: string;
        lastText: string;
        leftColumn: string;
        rightColumn: string;
        text: string;
        wrapper: string;
    }
}

declare const ControlModuleScssModule: ControlModuleScssNamespace.IControlModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ControlModuleScssNamespace.IControlModuleScss;
};

export = ControlModuleScssModule;
