// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace SymlayersModuleScssNamespace {
    export interface ISymlayersModuleScss {
        createButton: string;
        form: string;
        root: string;
    }
}

declare const SymlayersModuleScssModule: SymlayersModuleScssNamespace.ISymlayersModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: SymlayersModuleScssNamespace.ISymlayersModuleScss;
};

export = SymlayersModuleScssModule;
