// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace CreateVarModalModuleScssNamespace {
  export interface ICreateVarModalModuleScss {
    button: string;
    buttonsWrapper: string;
    dialog: string;
    input: string;
    name: string;
  }
}

declare const CreateVarModalModuleScssModule: CreateVarModalModuleScssNamespace.ICreateVarModalModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: CreateVarModalModuleScssNamespace.ICreateVarModalModuleScss;
};

export = CreateVarModalModuleScssModule;
