// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace CreateVarModalModuleScssNamespace {
  export interface ICreateVarModalModuleScss {
    arrow: string;
    button: string;
    buttonsWrapper: string;
    dialog: string;
    dropDownItem: string;
    form: string;
    icon: string;
    input: string;
    objectPropertiesBlock: string;
    select: string;
    selectData: string;
    selectField: string;
    selectedIconText: string;
    text: string;
    title: string;
    type: string;
    types: string;
    wrapperForm: string;
  }
}

declare const CreateVarModalModuleScssModule: CreateVarModalModuleScssNamespace.ICreateVarModalModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: CreateVarModalModuleScssNamespace.ICreateVarModalModuleScss;
};

export = CreateVarModalModuleScssModule;
