// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ReportSidebarModuleScssNamespace {
    export interface IReportSidebarModuleScss {
        actions: string;
        arrow: string;
        content: string;
        contentData: string;
        editActiveText: string;
        editBlock: string;
        editBlockActive: string;
        editBlockActiveCollapsed: string;
        editBlockCollapsed: string;
        editText: string;
        editableItem: string;
        objects: string;
        root: string;
        rotate: string;
        sidePanel: string;
        sidePanelVisible: string;
        tableActions: string;
        tableFilters: string;
        tabs: string;
        viewActiveText: string;
        viewBlock: string;
        viewBlockActive: string;
        viewBlockActiveCollapsed: string;
        viewItem: string;
        viewText: string;
    }
}

declare const ReportSidebarModuleScssModule: ReportSidebarModuleScssNamespace.IReportSidebarModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ReportSidebarModuleScssNamespace.IReportSidebarModuleScss;
};

export = ReportSidebarModuleScssModule;
