// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace NavigationModuleScssNamespace {
    export interface INavigationModuleScss {
        list: string;
        text: string;
        wrapper: string;
    }
}

declare const NavigationModuleScssModule: NavigationModuleScssNamespace.INavigationModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: NavigationModuleScssNamespace.INavigationModuleScss;
};

export = NavigationModuleScssModule;
