// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace PanelListItemModuleScssNamespace {
    export interface IPanelListItemModuleScss {
        folder: string;
        listItem: string;
        listItemIcon: string;
        listItemText: string;
    }
}

declare const PanelListItemModuleScssModule: PanelListItemModuleScssNamespace.IPanelListItemModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: PanelListItemModuleScssNamespace.IPanelListItemModuleScss;
};

export = PanelListItemModuleScssModule;
