// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ModalModuleScssNamespace {
    export interface IModalModuleScss {
        animatetop: string;
        appear: string;
        close: string;
        modal: string;
        modalBody: string;
        modalBodyWithScroll: string;
        modalClose: string;
        modalConfirmButtons: string;
        modalConfirmHeader: string;
        modalConfirmHeaderTitle: string;
        modalConfirmMiddle: string;
        modalConfirmMiddleTop: string;
        modalConfirmWrapper: string;
        modalConfirmWrapperConfirmButton: string;
        modalContent: string;
        modalDialog: string;
        modalDialogWithScroll: string;
        modalFooter: string;
        modalHeader: string;
        modalTitle: string;
        modalWithScroll: string;
        slideIn: string;
    }
}

declare const ModalModuleScssModule: ModalModuleScssNamespace.IModalModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ModalModuleScssNamespace.IModalModuleScss;
};

export = ModalModuleScssModule;
