// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ObjectsPaneActionsModuleScssNamespace {
    export interface IObjectsPaneActionsModuleScss {
        filtersGroup: string;
        iconBtn: string;
        input: string;
        root: string;
        searchGroup: string;
    }
}

declare const ObjectsPaneActionsModuleScssModule: ObjectsPaneActionsModuleScssNamespace.IObjectsPaneActionsModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ObjectsPaneActionsModuleScssNamespace.IObjectsPaneActionsModuleScss;
};

export = ObjectsPaneActionsModuleScssModule;
