// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace RadioModuleScssNamespace {
    export interface IRadioModuleScss {
        container: string;
        input: string;
        label: string;
        mark: string;
        wrapper: string;
    }
}

declare const RadioModuleScssModule: RadioModuleScssNamespace.IRadioModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: RadioModuleScssNamespace.IRadioModuleScss;
};

export = RadioModuleScssModule;
