// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace QueryPanelControlsModuleScssNamespace {
    export interface IQueryPanelControlsModuleScss {
        apply: string;
        buttonsWrapper: string;
        cancel: string;
        run: string;
        sql: string;
    }
}

declare const QueryPanelControlsModuleScssModule: QueryPanelControlsModuleScssNamespace.IQueryPanelControlsModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: QueryPanelControlsModuleScssNamespace.IQueryPanelControlsModuleScss;
};

export = QueryPanelControlsModuleScssModule;
