// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace SortingFieldModuleScssNamespace {
    export interface ISortingFieldModuleScss {
        closeIcon: string;
        root: string;
        select: string;
    }
}

declare const SortingFieldModuleScssModule: SortingFieldModuleScssNamespace.ISortingFieldModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: SortingFieldModuleScssNamespace.ISortingFieldModuleScss;
};

export = SortingFieldModuleScssModule;
