// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ReportObjectsPanelModuleScssNamespace {
    export interface IReportObjectsPanelModuleScss {
        panelListContainer: string;
        report: string;
    }
}

declare const ReportObjectsPanelModuleScssModule: ReportObjectsPanelModuleScssNamespace.IReportObjectsPanelModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ReportObjectsPanelModuleScssNamespace.IReportObjectsPanelModuleScss;
};

export = ReportObjectsPanelModuleScssModule;
