export const REPORT_DESIGNER_PAGE = "REPORT_DESIGNER_PAGE";
export const UNIVERSE_DESIGNER_PAGE = "UNIVERSE_DESIGNER_PAGE";
export const REPORT_WIZARD_PAGE = "REPORT_WIZARD_PAGE";
export const DASHBOARD_PAGE = "DASHBOARD_PAGE";
export const CONNECTORS_PAGE = "CONNECTORS_PAGE";
