/* eslint-disable import/prefer-default-export */
export const PAGE = {
  REPORT_DESIGNER: 'REPORT_DESIGNER',
  UNIVERSE_DESIGNER: 'UNIVERSE_DESIGNER',
  REPORT_WIZARD: 'REPORT_WIZARD',
  DASHBOARD: 'DASHBOARD',
  CONNECTORS: 'CONNECTORS',
  AUDIT: 'AUDIT',
  TRASH: 'TRASH',
  SEMANTIC: 'SEMANTIC',
  SEMANTIC_LIST: 'SEMANTIC_LIST',
  ROLES: 'ROLES',
  USERS: 'USERS',
  EXPLORER: 'EXPLORER',
  QUERY_PANEL: 'QUERY_PANEL',
};
