export const QUERY_PANEL_MODAL = 'QUERY_PANEL_MODAL';
export const QUERY_PANEL_POPUP = 'QUERY_PANEL_POPUP'; // TODO удалить, когда появится новый попап
export const CONNECTOR_POPUP = 'CONNECTOR_POPUP';
export const UNIVERSE_POPUP = 'UNIVERSE_POPUP';
export const UNIVERSE_MODAL = 'UNIVERSE_MODAL';
export const REPORT_WIZARD_POPUP = 'REPORT_WIZARD_POPUP';
export const OBJECTS_CONNECTIONS_MODAL = 'OBJECTS_CONNECTIONS_MODAL';
export const TABLE_PREVIEW_MODAL = 'TABLE_PREVIEW_MODAL';
