export const QUERY_PANEL_POPUP = 'QUERY_PANEL_POPUP';
export const CONNECTOR_POPUP = 'CONNECTOR_POPUP';
export const UNIVERSE_POPUP = 'UNIVERSE_POPUP';
export const REPORT_WIZARD_POPUP = 'REPORT_WIZARD_POPUP';