// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ReportObjectsPanelFiltersModuleScssNamespace {
    export interface IReportObjectsPanelFiltersModuleScss {
        actionWrapper: string;
        filterNameInput: string;
        magnifier: string;
        root: string;
    }
}

declare const ReportObjectsPanelFiltersModuleScssModule: ReportObjectsPanelFiltersModuleScssNamespace.IReportObjectsPanelFiltersModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ReportObjectsPanelFiltersModuleScssNamespace.IReportObjectsPanelFiltersModuleScss;
};

export = ReportObjectsPanelFiltersModuleScssModule;
