// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace SearchModuleScssNamespace {
    export interface ISearchModuleScss {
        btn: string;
        searchForm: string;
        searchInput: string;
    }
}

declare const SearchModuleScssModule: SearchModuleScssNamespace.ISearchModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: SearchModuleScssNamespace.ISearchModuleScss;
};

export = SearchModuleScssModule;
