// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace TableHeaderModuleScssNamespace {
    export interface ITableHeaderModuleScss {
        root: string;
    }
}

declare const TableHeaderModuleScssModule: TableHeaderModuleScssNamespace.ITableHeaderModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: TableHeaderModuleScssNamespace.ITableHeaderModuleScss;
};

export = TableHeaderModuleScssModule;
