// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace TextInputModuleScssNamespace {
    export interface ITextInputModuleScss {
        error: string;
        fullWidth: string;
        input: string;
        inputLabel: string;
        inputRequired: string;
        inputWrapper: string;
        textError: string;
    }
}

declare const TextInputModuleScssModule: TextInputModuleScssNamespace.ITextInputModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: TextInputModuleScssNamespace.ITextInputModuleScss;
};

export = TextInputModuleScssModule;
