// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace LoginPageModuleScssNamespace {
    export interface ILoginPageModuleScss {
        avatar: string;
        box: string;
        btn: string;
        form: string;
        inputWrapper: string;
        textInput: string;
    }
}

declare const LoginPageModuleScssModule: LoginPageModuleScssNamespace.ILoginPageModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: LoginPageModuleScssNamespace.ILoginPageModuleScss;
};

export = LoginPageModuleScssModule;
