export const CREATE_OBJECT_MODAL_VALUES = {
    NAME: 'name',
    OBJECT_DATA_TYPE: 'objectDataType',
    OBJECT_TYPE: 'objectType',
    OBJECT_FUNCTION: 'objectFunction',
    OBJECT_DESCRIPTION: 'objectDescription',
    SELECT_QUERY_FIELD: 'selectQueryField',
    WHERE_QUERY_FIELD: 'whereQueryField',
    DEFAULT_LINK_INPUT: 'defaultLinkInput',
    THIS_LIST_EDIT_CHECKBOX: 'thisListEditCheckBox',
    REFRESH_BEFORE_USAGE_CHECKBOX: 'refreshBeforeUsageCheckBox',
    SHOW_HIERARCHY_CHECKBOX: 'showHierarchyCheckBox',
    EXPORT_BY_UNIVERSE_CHECKBOX: 'exportByUniverseCheckBox',
    SEARCH_DELEGETION_CHECKBOX: 'searchDelegetionCheckBox',
    USAGE_PERMISSION: 'usagePermission',
    USE_IN_RESULTS_CHECKBOX: 'useInResultsCheckBox',
    USE_IN_CONDITIONS_CHECKBOX: 'useInConditionsCheckBox',
    USE_IN_SORTINGS_CHECKBOX: 'useInSortingsCheckBox',
    KEYS_DATA_TYPE: 'keysDataType',
    KEYS_TYPE: 'keysType',
    KEYS_SELECT_INPUT: 'keysSelectInput',
    KEYS_WHERE_INPUT: 'keysWhereInput',
    TECH_INFO_INPUT: 'techInfoInput',
    DISPLAY_INPUT: 'displayInput',
    ORIGIN_INPUT: 'originInput',
};
