// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace CreateObjectLayerModalModuleScssNamespace {
    export interface ICreateObjectLayerModalModuleScss {
        dialog: string;
        input: string;
        name: string;
    }
}

declare const CreateObjectLayerModalModuleScssModule: CreateObjectLayerModalModuleScssNamespace.ICreateObjectLayerModalModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: CreateObjectLayerModalModuleScssNamespace.ICreateObjectLayerModalModuleScss;
};

export = CreateObjectLayerModalModuleScssModule;
