// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ButtonModuleScssNamespace {
    export interface IButtonModuleScss {
        bigBlue: string;
        bigButtonFont: string;
        bigGray: string;
        bigOrange: string;
        bigRed: string;
        blue: string;
        brown: string;
        brownDarker: string;
        btn: string;
        disabled: string;
        gray: string;
        red: string;
        smallButtonFont: string;
        smallOrange: string;
    }
}

declare const ButtonModuleScssModule: ButtonModuleScssNamespace.IButtonModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ButtonModuleScssNamespace.IButtonModuleScss;
};

export = ButtonModuleScssModule;
