// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace SelectSemanticLayerModuleScssNamespace {
    export interface ISelectSemanticLayerModuleScss {
        dialog: string;
        disNavigationActions: string;
        header: string;
        modalBody: string;
        modalContent: string;
        navigationActions: string;
        reloadIcon: string;
        search: string;
        semanticItem: string;
        title: string;
    }
}

declare const SelectSemanticLayerModuleScssModule: SelectSemanticLayerModuleScssNamespace.ISelectSemanticLayerModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: SelectSemanticLayerModuleScssNamespace.ISelectSemanticLayerModuleScss;
};

export = SelectSemanticLayerModuleScssModule;
