// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ObjectsPanelHeaderModuleScssNamespace {
    export interface IObjectsPanelHeaderModuleScss {
        data: string;
        dataText: string;
        dropdownItem: string;
        header: string;
        indents: string;
        itemsWrapper: string;
        plusBtn: string;
        request: string;
        select: string;
    }
}

declare const ObjectsPanelHeaderModuleScssModule: ObjectsPanelHeaderModuleScssNamespace.IObjectsPanelHeaderModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ObjectsPanelHeaderModuleScssNamespace.IObjectsPanelHeaderModuleScss;
};

export = ObjectsPanelHeaderModuleScssModule;
