// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace FiltersDeskNodeModuleScssNamespace {
    export interface IFiltersDeskNodeModuleScss {
        conditionBlock: string;
        dndActive: string;
        itemsBlock: string;
        root: string;
        selected: string;
    }
}

declare const FiltersDeskNodeModuleScssModule: FiltersDeskNodeModuleScssNamespace.IFiltersDeskNodeModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: FiltersDeskNodeModuleScssNamespace.IFiltersDeskNodeModuleScss;
};

export = FiltersDeskNodeModuleScssModule;
