// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace PanelListNodeModuleScssNamespace {
    export interface IPanelListNodeModuleScss {
        innerListNode: string;
        listNode: string;
        listNodeInnerList: string;
        root: string;
    }
}

declare const PanelListNodeModuleScssModule: PanelListNodeModuleScssNamespace.IPanelListNodeModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: PanelListNodeModuleScssNamespace.IPanelListNodeModuleScss;
};

export = PanelListNodeModuleScssModule;
