// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace EditLayerModalModuleScssNamespace {
    export interface IEditLayerModalModuleScss {
        buttons: string;
        root: string;
        title: string;
        warningMessage: string;
    }
}

declare const EditLayerModalModuleScssModule: EditLayerModalModuleScssNamespace.IEditLayerModalModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: EditLayerModalModuleScssNamespace.IEditLayerModalModuleScss;
};

export = EditLayerModalModuleScssModule;
