// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace SchemaTablesModuleScssNamespace {
  export interface ISchemaTablesModuleScss {
    headerData: string;
    headerTitle: string;
    previewModalHeader: string;
    previewTableHeader: string;
    scalePanel: string;
    scalePanelButton: string;
    scaleValueWrapper: string;
    tableHeaderTitle: string;
    tablePreviewContent: string;
    tablePreviewModal: string;
    tablePreviewTable: string;
    workArea: string;
  }
}

declare const SchemaTablesModuleScssModule: SchemaTablesModuleScssNamespace.ISchemaTablesModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: SchemaTablesModuleScssNamespace.ISchemaTablesModuleScss;
};

export = SchemaTablesModuleScssModule;
