// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace TableComponentModuleScssNamespace {
    export interface ITableComponentModuleScss {
        checkBox: string;
        list: string;
        root: string;
        selected: string;
        tableActions: string;
        tableCheckbox: string;
        tableContainer: string;
        tableContent: string;
        tableHead: string;
        tableItem: string;
        tableRow: string;
        tableType: string;
        tablesList: string;
        workZone: string;
    }
}

declare const TableComponentModuleScssModule: TableComponentModuleScssNamespace.ITableComponentModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: TableComponentModuleScssNamespace.ITableComponentModuleScss;
};

export = TableComponentModuleScssModule;
