// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ObjectsPaneModuleScssNamespace {
    export interface IObjectsPaneModuleScss {
        contentData: string;
        owner: string;
        ownerText: string;
        root: string;
    }
}

declare const ObjectsPaneModuleScssModule: ObjectsPaneModuleScssNamespace.IObjectsPaneModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ObjectsPaneModuleScssNamespace.IObjectsPaneModuleScss;
};

export = ObjectsPaneModuleScssModule;
