// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ParamsModuleScssNamespace {
    export interface IParamsModuleScss {
        add: string;
        addParamBlock: string;
        change: string;
        delete: string;
        input: string;
        inputWrapper: string;
        inputsWrapper: string;
        label: string;
        table: string;
        text: string;
        textBlock: string;
        title: string;
        titleBlock: string;
        wrapper: string;
        wrapperColumn: string;
    }
}

declare const ParamsModuleScssModule: ParamsModuleScssNamespace.IParamsModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ParamsModuleScssNamespace.IParamsModuleScss;
};

export = ParamsModuleScssModule;
