// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace AuditFiltersModuleScssNamespace {
    export interface IAuditFiltersModuleScss {
        actionTitle: string;
        checkBoxTitle: string;
        dateSelect: string;
        title: string;
    }
}

declare const AuditFiltersModuleScssModule: AuditFiltersModuleScssNamespace.IAuditFiltersModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: AuditFiltersModuleScssNamespace.IAuditFiltersModuleScss;
};

export = AuditFiltersModuleScssModule;
