// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ItemsListModalModuleScssNamespace {
    export interface IItemsListModalModuleScss {
        activeItem: string;
        button: string;
        buttonsWrapper: string;
        choose: string;
        chooseCountBlock: string;
        contentBlock: string;
        count: string;
        dialog: string;
        dots: string;
        heading: string;
        icons: string;
        iconsIndents: string;
        input: string;
        item: string;
        itemsWrapper: string;
        list: string;
        menu: string;
        modal: string;
        modalBody: string;
        modalContent: string;
        search: string;
        searchBlock: string;
        text: string;
        title: string;
        topBlock: string;
    }
}

declare const ItemsListModalModuleScssModule: ItemsListModalModuleScssNamespace.IItemsListModalModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ItemsListModalModuleScssNamespace.IItemsListModalModuleScss;
};

export = ItemsListModalModuleScssModule;
