// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ObjectsPanelFiltersModuleScssNamespace {
    export interface IObjectsPanelFiltersModuleScss {
        filterNameInput: string;
        iconBtn: string;
        root: string;
    }
}

declare const ObjectsPanelFiltersModuleScssModule: ObjectsPanelFiltersModuleScssNamespace.IObjectsPanelFiltersModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ObjectsPanelFiltersModuleScssNamespace.IObjectsPanelFiltersModuleScss;
};

export = ObjectsPanelFiltersModuleScssModule;
