// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace GearsModuleScssNamespace {
    export interface IGearsModuleScss {
        circles: string;
        crcA1: string;
        crcA2: string;
        inherit: string;
        no1: string;
        no2: string;
        no3: string;
        stop: string;
    }
}

declare const GearsModuleScssModule: GearsModuleScssNamespace.IGearsModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: GearsModuleScssNamespace.IGearsModuleScss;
};

export = GearsModuleScssModule;
