// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace FiltersDeskItemModuleScssNamespace {
    export interface IFiltersDeskItemModuleScss {
        active: string;
        arrow: string;
        closeBtn: string;
        closeBtnIcon: string;
        icon: string;
        input: string;
        optionsText: string;
        optionsWrapper: string;
        root: string;
        select: string;
        selectText: string;
        selected: string;
        textContent: string;
        title: string;
    }
}

declare const FiltersDeskItemModuleScssModule: FiltersDeskItemModuleScssNamespace.IFiltersDeskItemModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: FiltersDeskItemModuleScssNamespace.IFiltersDeskItemModuleScss;
};

export = FiltersDeskItemModuleScssModule;
