// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ListItemEditModuleScssNamespace {
    export interface IListItemEditModuleScss {
        listItemEdit: string;
        listItemEditForm: string;
    }
}

declare const ListItemEditModuleScssModule: ListItemEditModuleScssNamespace.IListItemEditModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ListItemEditModuleScssNamespace.IListItemEditModuleScss;
};

export = ListItemEditModuleScssModule;
