// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace AccordionModuleScssNamespace {
    export interface IAccordionModuleScss {
        arrowActive: string;
        content: string;
        contentNoPadding: string;
        divider: string;
        item: string;
        title: string;
    }
}

declare const AccordionModuleScssModule: AccordionModuleScssNamespace.IAccordionModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: AccordionModuleScssNamespace.IAccordionModuleScss;
};

export = AccordionModuleScssModule;
