// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace TablesPaneActionsModuleScssNamespace {
    export interface ITablesPaneActionsModuleScss {
        btnGroup: string;
        iconBtn: string;
        root: string;
        searchGroup: string;
        searchInput: string;
    }
}

declare const TablesPaneActionsModuleScssModule: TablesPaneActionsModuleScssNamespace.ITablesPaneActionsModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: TablesPaneActionsModuleScssNamespace.ITablesPaneActionsModuleScss;
};

export = TablesPaneActionsModuleScssModule;
