// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace TabsItemModuleScssNamespace {
    export interface ITabsItemModuleScss {
        active: string;
        tabItemContainer: string;
        tabsItem: string;
    }
}

declare const TabsItemModuleScssModule: TabsItemModuleScssNamespace.ITabsItemModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: TabsItemModuleScssNamespace.ITabsItemModuleScss;
};

export = TabsItemModuleScssModule;
