// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ReportBodyModuleScssNamespace {
    export interface IReportBodyModuleScss {
        root: string;
    }
}

declare const ReportBodyModuleScssModule: ReportBodyModuleScssNamespace.IReportBodyModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ReportBodyModuleScssNamespace.IReportBodyModuleScss;
};

export = ReportBodyModuleScssModule;
