// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace FloatingButtonModuleScssNamespace {
    export interface IFloatingButtonModuleScss {
        btn: string;
        icon: string;
        label: string;
    }
}

declare const FloatingButtonModuleScssModule: FloatingButtonModuleScssNamespace.IFloatingButtonModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: FloatingButtonModuleScssNamespace.IFloatingButtonModuleScss;
};

export = FloatingButtonModuleScssModule;
