// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ListTableRowModuleScssNamespace {
    export interface IListTableRowModuleScss {
        active: string;
        content: string;
        icon: string;
        name: string;
        tableRow: string;
        tooltip: string;
    }
}

declare const ListTableRowModuleScssModule: ListTableRowModuleScssNamespace.IListTableRowModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ListTableRowModuleScssNamespace.IListTableRowModuleScss;
};

export = ListTableRowModuleScssModule;
