// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace KeysBlockModuleScssNamespace {
    export interface IKeysBlockModuleScss {
        arrow: string;
        checkBox: string;
        checkBoxDiv: string;
        ddData: string;
        ddField: string;
        defaulTypetIcon: string;
        defaultIcon: string;
        dropDownBlock: string;
        dropDownDataBlock: string;
        dropDownItem: string;
        dropDownText: string;
        footerGroup: string;
        keyTable: string;
        keyTableBlock: string;
        keysBlock: string;
        keysBlockSelectWhereInput: string;
        keysBtn: string;
        keysTableTitle: string;
        keysTitle: string;
        manageKeysGroup: string;
        mark: string;
        pencilIcon: string;
        selectDiv: string;
        selectGroup: string;
        selectInputGroup: string;
        selectedIconText: string;
        smallText: string;
        tableGroup: string;
        tableSelect: string;
        tableText: string;
        tableTitle: string;
        tableTitleDivider: string;
        tableTitleMr2: string;
        tableTitleMr33: string;
        tableTitleMr95: string;
        tableType: string;
        tableWhere: string;
        typeGroup: string;
        typeSelect: string;
        whereDiv: string;
        whereInputGroup: string;
    }
}

declare const KeysBlockModuleScssModule: KeysBlockModuleScssNamespace.IKeysBlockModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: KeysBlockModuleScssNamespace.IKeysBlockModuleScss;
};

export = KeysBlockModuleScssModule;
