// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace FilterPanelModuleScssNamespace {
    export interface IFilterPanelModuleScss {
        actionTitle: string;
        buttonClose: string;
        checkBoxTitle: string;
        root: string;
        title: string;
    }
}

declare const FilterPanelModuleScssModule: FilterPanelModuleScssNamespace.IFilterPanelModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: FilterPanelModuleScssNamespace.IFilterPanelModuleScss;
};

export = FilterPanelModuleScssModule;
