// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace PreloaderModuleScssNamespace {
    export interface IPreloaderModuleScss {
        logo: string;
        preloader: string;
        preloaderText: string;
        rotation: string;
    }
}

declare const PreloaderModuleScssModule: PreloaderModuleScssNamespace.IPreloaderModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: PreloaderModuleScssNamespace.IPreloaderModuleScss;
};

export = PreloaderModuleScssModule;
