// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace RecycleBinModuleScssNamespace {
    export interface IRecycleBinModuleScss {
        button: string;
        root: string;
    }
}

declare const RecycleBinModuleScssModule: RecycleBinModuleScssNamespace.IRecycleBinModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: RecycleBinModuleScssNamespace.IRecycleBinModuleScss;
};

export = RecycleBinModuleScssModule;
