// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ListNavBarViewTogglerModuleScssNamespace {
    export interface IListNavBarViewTogglerModuleScss {
        btn: string;
        multicolumnView: string;
        tableView: string;
        viewToggle: string;
    }
}

declare const ListNavBarViewTogglerModuleScssModule: ListNavBarViewTogglerModuleScssNamespace.IListNavBarViewTogglerModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ListNavBarViewTogglerModuleScssNamespace.IListNavBarViewTogglerModuleScss;
};

export = ListNavBarViewTogglerModuleScssModule;
