// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace CheckBoxModuleScssNamespace {
    export interface ICheckBoxModuleScss {
        blueBgColor: string;
        container: string;
        input: string;
        label: string;
        mark: string;
        wrapper: string;
    }
}

declare const CheckBoxModuleScssModule: CheckBoxModuleScssNamespace.ICheckBoxModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: CheckBoxModuleScssNamespace.ICheckBoxModuleScss;
};

export = CheckBoxModuleScssModule;
