// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace CommentsModuleScssNamespace {
    export interface ICommentsModuleScss {
        avatarBlock: string;
        basket: string;
        commentField: string;
        comments: string;
        date: string;
        info: string;
        listIcon: string;
        text: string;
        textarea: string;
        top: string;
        wrapper: string;
    }
}

declare const CommentsModuleScssModule: CommentsModuleScssNamespace.ICommentsModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: CommentsModuleScssNamespace.ICommentsModuleScss;
};

export = CommentsModuleScssModule;
