// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace FiltersHeaderModuleScssNamespace {
    export interface IFiltersHeaderModuleScss {
        btnGroup: string;
        iconBtn: string;
        root: string;
        title: string;
    }
}

declare const FiltersHeaderModuleScssModule: FiltersHeaderModuleScssNamespace.IFiltersHeaderModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: FiltersHeaderModuleScssNamespace.IFiltersHeaderModuleScss;
};

export = FiltersHeaderModuleScssModule;
