// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace TopBarModuleScssNamespace {
    export interface ITopBarModuleScss {
        actions: string;
        header: string;
        logo: string;
        logoText: string;
        userMenuWrapper: string;
    }
}

declare const TopBarModuleScssModule: TopBarModuleScssNamespace.ITopBarModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: TopBarModuleScssNamespace.ITopBarModuleScss;
};

export = TopBarModuleScssModule;
