// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ConnectModuleScssNamespace {
    export interface IConnectModuleScss {
        buttonsWrapper: string;
        edit: string;
        gearsIcon: string;
        hide: string;
        iconWrapper: string;
        test: string;
        text: string;
        wireIcon: string;
        wrapper: string;
    }
}

declare const ConnectModuleScssModule: ConnectModuleScssNamespace.IConnectModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ConnectModuleScssNamespace.IConnectModuleScss;
};

export = ConnectModuleScssModule;
