// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ListColumnsViewModuleScssNamespace {
    export interface IListColumnsViewModuleScss {
        listColumnsView: string;
    }
}

declare const ListColumnsViewModuleScssModule: ListColumnsViewModuleScssNamespace.IListColumnsViewModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ListColumnsViewModuleScssNamespace.IListColumnsViewModuleScss;
};

export = ListColumnsViewModuleScssModule;
