// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace DeleteItemModalModuleScssNamespace {
    export interface IDeleteItemModalModuleScss {
        footer: string;
        message: string;
        title: string;
    }
}

declare const DeleteItemModalModuleScssModule: DeleteItemModalModuleScssNamespace.IDeleteItemModalModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: DeleteItemModalModuleScssNamespace.IDeleteItemModalModuleScss;
};

export = DeleteItemModalModuleScssModule;
