// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace TextFieldItemModuleScssNamespace {
    export interface ITextFieldItemModuleScss {
        input: string;
    }
}

declare const TextFieldItemModuleScssModule: TextFieldItemModuleScssNamespace.ITextFieldItemModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: TextFieldItemModuleScssNamespace.ITextFieldItemModuleScss;
};

export = TextFieldItemModuleScssModule;
