// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ObjectsConnectionsEditorModuleScssNamespace {
    export interface IObjectsConnectionsEditorModuleScss {
        buttonsWrapper: string;
        checkBoxWrapper: string;
        columnTitle: string;
        connectImagesWrapper: string;
        connectTypeBlock: string;
        connectionSelect: string;
        connectionTypeText: string;
        connectionsWrapper: string;
        dialog: string;
        editButton: string;
        expressionBox: string;
        expressionTitle: string;
        expressionWrapper: string;
        formulaButtons: string;
        formulaLeftSide: string;
        gearsIcon: string;
        iconWrapper: string;
        modalBody: string;
        modalContent: string;
        modalWrapper: string;
        optRed: string;
        outsideConnectCheckbox: string;
        save: string;
        selectColumn: string;
        sqlDialog: string;
        sqlFunctionDescText: string;
        sqlFunctionDescription: string;
        sqlFunctions: string;
        sqlMainContent: string;
        sqlModalWrapper: string;
        sqlOperators: string;
        sqlTables: string;
        switchSide: string;
        tableColumnName: string;
        tableContent: string;
        tableName: string;
        tablesWrapper: string;
        testButton: string;
    }
}

declare const ObjectsConnectionsEditorModuleScssModule: ObjectsConnectionsEditorModuleScssNamespace.IObjectsConnectionsEditorModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ObjectsConnectionsEditorModuleScssNamespace.IObjectsConnectionsEditorModuleScss;
};

export = ObjectsConnectionsEditorModuleScssModule;
