// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace PropertiesModuleScssNamespace {
    export interface IPropertiesModuleScss {
        checkbox: string;
        label: string;
        textBold: string;
        textContainer: string;
        textWrapper: string;
    }
}

declare const PropertiesModuleScssModule: PropertiesModuleScssNamespace.IPropertiesModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: PropertiesModuleScssNamespace.IPropertiesModuleScss;
};

export = PropertiesModuleScssModule;
