// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace TabsModuleScssNamespace {
    export interface ITabsModuleScss {
        tabsContainer: string;
        tabsContent: string;
        tabsHeader: string;
    }
}

declare const TabsModuleScssModule: TabsModuleScssNamespace.ITabsModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: TabsModuleScssNamespace.ITabsModuleScss;
};

export = TabsModuleScssModule;
