// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ObjectsPanelListModuleScssNamespace {
    export interface IObjectsPanelListModuleScss {
        innerListNode: string;
        root: string;
    }
}

declare const ObjectsPanelListModuleScssModule: ObjectsPanelListModuleScssNamespace.IObjectsPanelListModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ObjectsPanelListModuleScssNamespace.IObjectsPanelListModuleScss;
};

export = ObjectsPanelListModuleScssModule;
