// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace InlinePreloaderModuleScssNamespace {
    export interface IInlinePreloaderModuleScss {
        dot: string;
        dots: string;
        gooey: string;
    }
}

declare const InlinePreloaderModuleScssModule: InlinePreloaderModuleScssNamespace.IInlinePreloaderModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: InlinePreloaderModuleScssNamespace.IInlinePreloaderModuleScss;
};

export = InlinePreloaderModuleScssModule;
