// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace BlockModuleScssNamespace {
    export interface IBlockModuleScss {
        graph: string;
        handler: string;
        handlerE: string;
        handlerN: string;
        handlerNe: string;
        handlerNw: string;
        handlerS: string;
        handlerSe: string;
        handlerSw: string;
        handlerW: string;
        isActive: string;
        root: string;
        shape: string;
        text: string;
    }
}

declare const BlockModuleScssModule: BlockModuleScssNamespace.IBlockModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: BlockModuleScssNamespace.IBlockModuleScss;
};

export = BlockModuleScssModule;
