// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace HomePageButtonModuleScssNamespace {
    export interface IHomePageButtonModuleScss {
        buttonText: string;
        buttonTextApps: string;
        homePageButton: string;
        homePageButtonWrapper: string;
        homePageDocumentButton: string;
    }
}

declare const HomePageButtonModuleScssModule: HomePageButtonModuleScssNamespace.IHomePageButtonModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: HomePageButtonModuleScssNamespace.IHomePageButtonModuleScss;
};

export = HomePageButtonModuleScssModule;
