// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace SideBarTabContentModuleScssNamespace {
    export interface ISideBarTabContentModuleScss {
        description: string;
        icon: string;
        title: string;
        titleGroup: string;
    }
}

declare const SideBarTabContentModuleScssModule: SideBarTabContentModuleScssNamespace.ISideBarTabContentModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: SideBarTabContentModuleScssNamespace.ISideBarTabContentModuleScss;
};

export = SideBarTabContentModuleScssModule;
