// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace HomePageModuleScssNamespace {
    export interface IHomePageModuleScss {
        apps: string;
        appsBg: string;
        favoritesBg: string;
        recentBg: string;
        root: string;
        row: string;
        rowTitle: string;
        section: string;
        whiteLine: string;
        whiteLine2: string;
        whiteLine3: string;
        whiteLineShadow: string;
    }
}

declare const HomePageModuleScssModule: HomePageModuleScssNamespace.IHomePageModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: HomePageModuleScssNamespace.IHomePageModuleScss;
};

export = HomePageModuleScssModule;
