// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace DropdownModuleScssNamespace {
    export interface IDropdownModuleScss {
        dropDownItem: string;
        icon: string;
        itemsWrapper: string;
        mainButton: string;
        overlay: string;
        wrapper: string;
    }
}

declare const DropdownModuleScssModule: DropdownModuleScssNamespace.IDropdownModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: DropdownModuleScssNamespace.IDropdownModuleScss;
};

export = DropdownModuleScssModule;
