// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace SqlPopupModuleScssNamespace {
    export interface ISqlPopupModuleScss {
        buttons: string;
        dialog: string;
        exit: string;
        queryField: string;
        sql: string;
        test: string;
    }
}

declare const SqlPopupModuleScssModule: SqlPopupModuleScssNamespace.ISqlPopupModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: SqlPopupModuleScssNamespace.ISqlPopupModuleScss;
};

export = SqlPopupModuleScssModule;
