// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace DeleteObjectModalModuleScssNamespace {
    export interface IDeleteObjectModalModuleScss {
        footer: string;
        message: string;
        title: string;
    }
}

declare const DeleteObjectModalModuleScssModule: DeleteObjectModalModuleScssNamespace.IDeleteObjectModalModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: DeleteObjectModalModuleScssNamespace.IDeleteObjectModalModuleScss;
};

export = DeleteObjectModalModuleScssModule;
