// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ConnectorsModuleScssNamespace {
    export interface IConnectorsModuleScss {
        actions: string;
        cancelButton: string;
        connectionTypeInputsWrapper: string;
        connectionTypeSection: string;
        connectionTypeSelect: string;
        connectionTypeWrapper: string;
        connectionWrapper: string;
        connectorsInput: string;
        connectorsLabel: string;
        createButton: string;
        footerButtonsGroup: string;
        form: string;
        gearsIconWrapper: string;
        modalContent: string;
        root: string;
        selectInput: string;
        selectText: string;
        selectTypeConnection: string;
        showTestFailed: string;
        testConnectionButton: string;
        testConnectionWrapper: string;
        testConnectorButton: string;
        testOkIcon: string;
        textAreaName: string;
        textarea: string;
    }
}

declare const ConnectorsModuleScssModule: ConnectorsModuleScssNamespace.IConnectorsModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ConnectorsModuleScssNamespace.IConnectorsModuleScss;
};

export = ConnectorsModuleScssModule;
