// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace DataTableModuleScssNamespace {
    export interface IDataTableModuleScss {
        activeCol: string;
        table: string;
        tableContainer: string;
    }
}

declare const DataTableModuleScssModule: DataTableModuleScssNamespace.IDataTableModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: DataTableModuleScssNamespace.IDataTableModuleScss;
};

export = DataTableModuleScssModule;
