// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ReportObjectsPanelModuleScssNamespace {
  export interface IReportObjectsPanelModuleScss {
    actionWrapper: string;
    activeListItem: string;
    block: string;
    container: string;
    dropdownItem: string;
    filterNameInput: string;
    icon: string;
    iconIndents: string;
    innerBlock: string;
    innerText: string;
    itemsWrapper: string;
    listItem: string;
    magnifier: string;
    report: string;
    root: string;
    simpleDropDown: string;
    text: string;
    title: string;
    wrapper: string;
    wrapperBlock: string;
    wrapperInner: string;
  }
}

declare const ReportObjectsPanelModuleScssModule: ReportObjectsPanelModuleScssNamespace.IReportObjectsPanelModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ReportObjectsPanelModuleScssNamespace.IReportObjectsPanelModuleScss;
};

export = ReportObjectsPanelModuleScssModule;
