// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ReportContentModuleScssNamespace {
    export interface IReportContentModuleScss {
        root: string;
    }
}

declare const ReportContentModuleScssModule: ReportContentModuleScssNamespace.IReportContentModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ReportContentModuleScssNamespace.IReportContentModuleScss;
};

export = ReportContentModuleScssModule;
