// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace LayoutModuleScssNamespace {
    export interface ILayoutModuleScss {
        content: string;
        root: string;
    }
}

declare const LayoutModuleScssModule: LayoutModuleScssNamespace.ILayoutModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: LayoutModuleScssNamespace.ILayoutModuleScss;
};

export = LayoutModuleScssModule;
