// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace NotFoundPageModuleScssNamespace {
    export interface INotFoundPageModuleScss {
        root: string;
    }
}

declare const NotFoundPageModuleScssModule: NotFoundPageModuleScssNamespace.INotFoundPageModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: NotFoundPageModuleScssNamespace.INotFoundPageModuleScss;
};

export = NotFoundPageModuleScssModule;
