// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ReportActionsModuleScssNamespace {
    export interface IReportActionsModuleScss {
        actionWrapper: string;
        actionsContainer: string;
        divider: string;
        firstPage: string;
        firstPageText: string;
        graphTypes: string;
        iconsText: string;
        iconsWrapper: string;
        indents: string;
        inpitValue: string;
        input: string;
        lastPage: string;
        lastPageText: string;
        navigation: string;
        rotate: string;
        tableTypes: string;
        zoomSlider: string;
    }
}

declare const ReportActionsModuleScssModule: ReportActionsModuleScssNamespace.IReportActionsModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ReportActionsModuleScssNamespace.IReportActionsModuleScss;
};

export = ReportActionsModuleScssModule;
