// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace FormulaEditorModuleScssNamespace {
    export interface IFormulaEditorModuleScss {
        action: string;
        actions: string;
        input: string;
        root: string;
    }
}

declare const FormulaEditorModuleScssModule: FormulaEditorModuleScssNamespace.IFormulaEditorModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: FormulaEditorModuleScssNamespace.IFormulaEditorModuleScss;
};

export = FormulaEditorModuleScssModule;
