// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace DescriptionBlockModuleScssNamespace {
    export interface IDescriptionBlockModuleScss {
        descriptionInput: string;
        objectDescriptionBlock: string;
        title: string;
    }
}

declare const DescriptionBlockModuleScssModule: DescriptionBlockModuleScssNamespace.IDescriptionBlockModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: DescriptionBlockModuleScssNamespace.IDescriptionBlockModuleScss;
};

export = DescriptionBlockModuleScssModule;
